[package]
name = "decay_core"
version = "0.1.0"
authors = ["Mcp613 <40151628+Fullbrik@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.0"
