[package]
name = "decay_desktop"
version = "0.1.0"
authors = ["Mcp613 <40151628+Fullbrik@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.0"
serde_json = "1.0.64"
clap = "3.0.0-beta.2"
